### PR TITLE
Add service.nodePorts.http parameter to configure NodePort

### LINKED ISSUE #425: [feature request] Allow configuration of NodePort port number in all charts
Charts here expose `service.type` but do not allow configuration of an explicit NodePort when `service.type == "NodePort"`.

### PR DESCRIPTION
**Pull request by brsolomon-deloitte**
Closes #425.

### CODE REVIEW

**Comment by brsolomon-deloitte** [comment]
```
$ helm template -s templates/service.yaml --set service.type=NodePort --set service.nodePorts.http=31086 .
---
# Source: influxdb/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-influxdb
  labels:
    helm.sh/chart: influxdb-4.10.7
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.8.10"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
  - name: api
    port: 8086
    targetPort: api
    nodePort: 31086
  - name: rpc
    port: 8088
    targetPort: rpc
  selector:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/instance: release-name
```

**Comment by alespour** [comment]
LGTM, just curious what is `nodePort: null` good for in case of `ClusterIP` service type?

**Comment by brsolomon-deloitte** [comment]
> LGTM, just curious what is `nodePort: null` good for in case of `ClusterIP` service type?

That was unnecessary cruft - removed.

**Review by alespour — APPROVED** [review]
Thank you for the contribution!

**Review by ivankudibal — APPROVED** [review]

**Review by alespour — APPROVED** [review]

**Pull request merged**
