### PR TITLE
Add podLabels to influxdb's StatefulSet

### PR DESCRIPTION
**Pull request by andy-sokalau**
Why:
* Labels defined as podLabels in values do not get added to pods

How:
* Add podLabels to StatefulSet template

Tests:
```
$ cat /tmp/influx-values.yml
podLabels:
  influx/testlabel: testvalue
$ git --no-pager log --oneline -1
847f9a6 (HEAD -> influxdb-chart-utilize-pod-labels, tag: influxdb-4.10.0, upstream/master, origin/master, origin/HEAD, master) fix: tag conflicts existed, bumping version
$ git --no-pager diff upstream/master
$ helm install test-influxdb charts/influxdb --values /tmp/influx-values.yml > /dev/null
$ k get pods test-influxdb-0 -o json | jq '.metadata.labels'
{
  "app.kubernetes.io/instance": "test-influxdb",
  "app.kubernetes.io/name": "influxdb",
  "controller-revision-hash": "test-influxdb-866c48867f",
  "statefulset.kubernetes.io/pod-name": "test-influxdb-0"
}
$ helm uninstall test-influxdb > /dev/null
$ # ...changing the code...
$ git --no-pager diff upstream/master
diff --git a/charts/influxdb/templates/statefulset.yaml b/charts/influxdb/templates/statefulset.yaml
index 13eda03..e022b04 100644
--- a/charts/influxdb/templates/statefulset.yaml
+++ b/charts/influxdb/templates/statefulset.yaml
@@ -18,6 +18,9 @@ spec:
     metadata:
       labels:
         {{- include "influxdb.selectorLabels" . | nindent 8 }}
+      {{- if .Values.podLabels }}
+{{ toYaml .Values.podLabels | indent 8 }}
+      {{- end }}
       {{- if .Values.podAnnotations }}
       annotations:
 {{ toYaml .Values.podAnnotations | indent 8 }}
$ helm install test-influxdb charts/influxdb --values /tmp/influx-values.yml > /dev/null
$ k get pods test-influxdb-0 -o json | jq '.metadata.labels'
{
  "app.kubernetes.io/instance": "test-influxdb",
  "app.kubernetes.io/name": "influxdb",
  "controller-revision-hash": "test-influxdb-fb55556cc",
  "influx/testlabel": "testvalue",
  "statefulset.kubernetes.io/pod-name": "test-influxdb-0"
}
```

- [ ] CHANGELOG.md updated
- [ ] Rebased/mergable
- [ ] Tests pass
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by alespour** [comment]
Fixes #265

**Comment by alespour** [comment]
Thank you for the contribution. Could you please rebase and bump the chart version?

**Comment by andy-sokalau** [comment]
> Thank you for the contribution. Could you please rebase and bump chart version?

Done.

**Review by alespour — APPROVED** [review]
Looks good, thank you.

**Comment by timhallinflux** [comment]
@andy-sokalau -- I checked the CLA and cannot find your signature.  Can you please resubmit? https://www.influxdata.com/legal/cla/

**Comment by andy-sokalau** [comment]
@timhallinflux done

**Review by tomklapka — APPROVED** [review]

**Pull request merged**
