### PR TITLE
[influxdb-enterprise] add annotations to data.service

### PR DESCRIPTION
**Pull request by olibal**
- [ ] CHANGELOG.md updated
- [x] Rebased/mergable
- [x] Tests pass
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

It should be possible to ingest data to influxdb via cloud internal load balancer.

> To set an internal load balancer, add one of the following annotations to the Service depending on the cloud Service provider you're using. 

(ref. [https://kubernetes.io/docs](https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer))

**Example: Azure**

```
annotations: 
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
```

**Applied tests:**

```
helm lint ./influxdb-enterprise
```
resulted to:

```
==> Linting ./influxdb-enterprise
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed
```

```
helm template --set data.service.annotations.service\\.beta\\.kubernetes\\.io/azure-load-balancer-internal=true influxdb-enterprise ./influxdb-enterprise
```
resulted to (extract):
```
# Source: influxdb-enterprise/templates/data-service.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: true
  name: influxdb-enterprise-data
  labels:
    influxdb.influxdata.com/component: data
    helm.sh/chart: influxdb-enterprise-0.1.15
    app.kubernetes.io/name: influxdb-enterprise
    app.kubernetes.io/instance: influxdb-enterprise
    app.kubernetes.io/version: "1.9.6"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - port: 8086
    protocol: TCP
    name: http
  - port: 8088
    protocol: TCP
    name: rpc
  - port: 2003
    protocol: TCP
    name: graphite
  - port: 4242
    protocol: TCP
    name: opentsdb
  - port: 25826
    protocol: UDP
    name: collectd
  - port: 8089
    protocol: UDP
    name: udp
  selector:
    influxdb.influxdata.com/component: data
    app.kubernetes.io/name: influxdb-enterprise
    app.kubernetes.io/instance: influxdb-enterprise

```

### CODE REVIEW

**Comment by alespour** [comment]
Could you bump chart version, please? It is required for the check to pass. Thanks.

**Comment by olibal** [comment]
> Could you bump chart version, please? It is required for the check to pass. Thanks.

I have bumped influxdb-enterprise chart version to v0.1.16

**Comment by alespour** [comment]
@timhallinflux checks fail only because pull request from fork do not have access to repository secrets where enterprise license key is sotred

**Review by alespour — APPROVED** [review]

**Comment by tomklapka** [comment]
To make it complete, would it be possible to have annotations also in meta service ?

**Comment by olibal** [comment]
> tomklapka

**Comment by olibal** [comment]
Sorry, I closed this PR by accident and so I have re-opened it

**Comment by tomklapka** [comment]
> > To make it complete, would it be possible to have annotations also in meta service ?
> 
> Yes, sure, I've made the required changes for it to have it conistent to the data services

Thank you, and one last thing, in meta section in values.yaml should be also corresponding (commented) meta.service section to know users that this is possible to change in meta service too.

**Comment by olibal** [comment]
> > > To make it complete, would it be possible to have annotations also in meta service ?
> > 
> > 
> > Yes, sure, I've made the required changes for it to have it conistent to the data services
> 
> Thank you, and one last thing, in meta section in values.yaml should be also corresponding (commented) meta.service section to know users that this is possible to change in meta service too.

Good point, thx. I,ve updated to value.yaml and added a comment on meta.service.annotations

**Comment by tomklapka** [comment]
> > > > To make it complete, would it be possible to have annotations also in meta service ?
> > > 
> > > 
> > > Yes, sure, I've made the required changes for it to have it conistent to the data services
> > 
> > 
> > Thank you, and one last thing, in meta section in values.yaml should be also corresponding (commented) meta.service section to know users that this is possible to change in meta service too.
> 
> Good point, thx. I,ve updated to value.yaml and added a comment on meta.service.annotations

Please see checks and fix accordingly, thanks

**Comment by olibal** [comment]
> > > > > To make it complete, would it be possible to have annotations also in meta service ?
> > > > 
> > > > 
> > > > Yes, sure, I've made the required changes for it to have it conistent to the data services
> > > 
> > > 
> > > Thank you, and one last thing, in meta section in values.yaml should be also corresponding (commented) meta.service section to know users that this is possible to change in meta service too.
> > 
> > 
> > Good point, thx. I,ve updated to value.yaml and added a comment on meta.service.annotations
> 
> Please see checks and fix accordingly, thanks

fixed 

image

**Comment by olibal** [comment]
I have commented in "annotations: {}" for data.service: and meta.service to prevent nil pointer evaluating

**Comment by tomklapka** [comment]
> I have commented in "annotations: {}" for data.service: and meta.service to prevent nil pointer evaluating

If failed to null because service section is otherwise empty. For instance if you add `type: ClusterIP` (as same as in the data service) and then comment out annotations, it will work.

**Comment by olibal** [comment]
> > I have commented in "annotations: {}" for data.service: and meta.service to prevent nil pointer evaluating
> 
> If failed to null because service section is otherwise empty. For instance if you add `type: ClusterIP` (as same as in the data service) and then comment out annotations, it will work.

I made the changes ass you proposed. Nevertheless the test seemed failed due to Licence key issues in the test environment, which I cannot fix from my side. I don't have any key available. Any ideas how to solve this?

image

**Comment by tomklapka** [comment]
> > > I have commented in "annotations: {}" for data.service: and meta.service to prevent nil pointer evaluating
> > 
> > 
> > If failed to null because service section is otherwise empty. For instance if you add `type: ClusterIP` (as same as in the data service) and then comment out annotations, it will work.
> 
> I made the changes ass you proposed. Nevertheless the test seemed failed due to Licence key issues in the test environment, which I cannot fix from my side. I don't have any key available. Any ideas how to solve this?
> 
> image

That's ok, Github doesn't propagate secret variables to actions triggered from PRs.

**Review by tomklapka — APPROVED** [review]
Looks good to me, thank you for contribution

**Review by alespour — APPROVED** [review]

**Pull request merged**
