### PR TITLE
#227 [influxdb2] Install fails on influx setup

### PR DESCRIPTION
**Pull request by mproffitt**
As described in #227, the influxdb2 helm chart will fail if influxdb2 has already been configured on the persistent volume store.

Although not fool-proof, the simplest way to overcome this failure is to execute `influx org list -n {{ .Values.adminUser.organisation }}` and only if that fails, move on to execute influx setup.

I believe this would work in all instances except where a user has deleted the configured `adminUser.organisation`

- [ ] CHANGELOG.md updated
- [x] Rebased/mergable
- [ ] Tests pass
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by rawkode** [comment]
Thanks for taking a go at this.

I'm a little confused, as we use the install hook that should only be run for fresh installations.

`"helm.sh/hook": post-install`

This job shouldn't be created for upgrades.

**Comment by mproffitt** [comment]
The scenario I found this in was when changing namespaces for the pod but I think it would trigger in any scenario whereby the pod was destroyed / replaced without the underlying filesystem being stripped back.

Another scenario I'm currently facing which would trigger this failure is migrating deployments between distinct clusters.

Perhaps the term "upgrades" is a little too ambiguous - I changed namespaces and changed versions simultaneously and then spent most of last night really confused as to why it stopped installing.

**Comment by iamolegga** [comment]
Just faced the same issue, any updates?

**Comment by ondrej-ivanko** [comment]
The script can work on most occasions, but not in following scenario. 

Suppose you have persistent volume claim enabled and it's created after you install influx2 release in your namespace. Influx is set up ok with script. 
Than you uninstall influx and install it again. If you made any changes to values.yaml adminUser on your second install of release, than all those changes are ignored. Because the influx is already set up in your persistent volume claim. You have to removed the pvc with kubectl and than can install again.

But that's a Kubernetes thing, I dont think this chart can do anything about it.

**Comment by timhallinflux** [comment]
closing this in favor of #294

**Pull request closed without merging**
