### PR TITLE
telegraf-ds: add support setting dnsConfig

### PR DESCRIPTION
**Pull request by clwluvw**
This allow setting `dnsConfig` when `dnsPolicy` is set to None

Signed-off-by: Seena Fallah <seenafallah@gmail.com>

### CODE REVIEW

**Comment by alespour** [comment]
Could you bump chart version (to `1.0.25`), please.

**Review by alespour — DISMISSED** [review]
Tested & LGTM.

**Comment by clwluvw** [comment]
> Could you bump chart version (to `1.0.25`), please.

@alespour Done

**Review by timhallinflux — APPROVED** [review]

**Comment by timhallinflux** [comment]
@clwluvw -- It doesn't look like you've signed our CLA.  Please do so, before we can merge. https://www.influxdata.com/legal/cla/

**Comment by clwluvw** [comment]
> @clwluvw -- It doesn't look like you've signed our CLA. Please do so, before we can merge. https://www.influxdata.com/legal/cla/

@timhallinflux I've signed it.

**Pull request merged**
