### PR TITLE
chore: update Telegraf versions for v1.23.3

### PR DESCRIPTION
**Pull request by MyaLongmire**

### CODE REVIEW

**Comment by powersj** [comment]
@sspaink is there a spacing setting causing the extra white space changes?

**Comment by sspaink** [comment]
This is the result of the default spacing from the Go yaml package: https://gopkg.in/yaml.v3, it looks like there is a way to adjust the indent: https://pkg.go.dev/gopkg.in/yaml.v3#Encoder.SetIndent that maybe we can use to make the linter happy. Last PR I manually edited the files after setting up the chart testing tool that the github action uses (https://github.com/helm/chart-testing) was a bit more involved then I expected but it uses https://github.com/adrienverge/yamllint which I think is complaining about the indentions.

**Comment by MyaLongmire** [comment]
For now, I will manually adjust the indent and we can figure out our next steps internally.

**Review by sjwang90 — APPROVED** [review]

**Review by powersj — APPROVED** [review]

**Review by wojciechka — APPROVED** [review]

**Comment by sjwang90** [comment]
@wojciechka can you merge this?

**Pull request merged**
