### PR TITLE
Edit influxdb post-install note

### PR DESCRIPTION
**Pull request by pierwill**

### CODE REVIEW

**Comment by pierwill** [comment]
Hm... What's causing this conflict? 🤔

**Comment by rawkode** [comment]
@pierwill Chart needs bumped to 4.4.9

**Comment by pierwill** [comment]
I just used GitHub web UI "Resolve Conflicts" button. Not sure this is correct— 🤔

**Comment by pierwill** [comment]
I guess it basically did a rebase?

**Comment by rawkode** [comment]
@pierwill wasn't a rebase, as it added a merge commit. Once the tests run I'll get this good to go

Thanks

**Pull request merged**
