### PR TITLE
Fix telegraf-ds mounts

### PR DESCRIPTION
**Pull request by afausti**
Currently the Helm chart mounts `/proc` on `/rootfs/proc` but even after setting `HOST_PROC=/rootfs/proc` a `cat` on `/proc/self/mounts` or a `df` inside the container shows information for the container and not for the host.

Mounting the host filesystem following [this FAQ](https://github.com/influxdata/telegraf/blob/master/docs/FAQ.md#q-how-can-i-monitor-the-docker-engine-host-from-within-a-container) fixes it.

### CODE REVIEW

**Comment by afausti** [comment]
@rawkode in case you have time to review this. Thank you!

**Comment by mazzy89** [comment]
I'm interested to see this out because it is breaking the collection of disk info in my installation. Could we get this reviewed please thanks?

**Comment by mazzy89** [comment]
Can we please review this?

**Review by rawkode — APPROVED** [review]

**Comment by mazzy89** [comment]
Thanks a lot @rawkode

**Pull request merged**
