### PR TITLE
Add container environment variable configuration

### PR DESCRIPTION
**Pull request by rmeharg**
Allow configuration of container environment variables.

For greater flexibility and configuration of options found that are not explicitly exposed in the helm chart 

https://docs.influxdata.com/enterprise_influxdb/v1.8/administration/config-data-nodes/#data-node-configuration-settings

Our use case is for INFLUXDB_HTTP_FLUX_ENABLED

### CODE REVIEW

**Comment by rmeharg** [comment]
#294 is for influxdb2 only, and not the influxdb-enterprise chart

**Review by rawkode — DISMISSED** [review]

**Comment by rawkode** [comment]
Thank you, @rmeharg

**Review by timhallinflux — DISMISSED** [review]

**Comment by timhallinflux** [comment]
I think this needs a chart version bump...before we can merge.

**Comment by rmeharg** [comment]
Version bumped

**Review by timhallinflux — APPROVED** [review]

**Comment by timhallinflux** [comment]
@rmeharg looks like we've got one small issue with the linter -- can you have a look?

**Comment by rmeharg** [comment]
> @rmeharg looks like we've got one small issue with the linter -- can you have a look?

Sorry was due to extra newline, fixed

**Comment by timhallinflux** [comment]
@rmeharg linter still complaining about some spaces

**Comment by rmeharg** [comment]
> @rmeharg linter still complaining about some spaces

@timhallinflux I think this is a false positive as I didn't change this line, but I've made the fix 56d7948

**Comment by timhallinflux** [comment]
@rmeharg -- looks like there is another error detected by the linter.  Can you have a look?  I think that should be "it."

**Comment by rmeharg** [comment]
@timhallinflux think it should be fixed now, a customer is asking me if this can be merged? Thanks

**Review by timhallinflux — APPROVED** [review]

**Comment by brightstone9** [comment]
Is there any update on this PR? We also need have the option to set environment variable in influxdb-enterprise chart.

**Comment by timhallinflux** [comment]
@alespour please have a look?

**Comment by alespour** [comment]
Needs rebase. It may result in invalid `values`, since current version set `license: {}` (line 10) and this PR uncomments `key` and `secret` (lines 14-15).

**Comment by alespour** [comment]
Closed via #443

**Pull request closed without merging**
