### PR TITLE
Update for Chronograf 1.9.1

### PR DESCRIPTION
**Pull request by timhallinflux**

### CODE REVIEW

**Review by rawkode — APPROVED** [review]

**Comment by timhallinflux** [comment]
@rawkode any insight as to why the linter is failing?

**Comment by rawkode** [comment]
Image hasn't been pushed yet?

```
  Warning  Failed     3m30s (x4 over 4m59s)  kubelet            Failed to pull image "chronograf:1.9.1": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/library/chronograf:1.9.1": failed to resolve reference "docker.io/library/chronograf:1.9.1": docker.io/library/chronograf:1.9.1: not found
  Warning  Failed     3m30s (x4 over 4m59s)  kubelet            Error: ErrImagePull
  Warning  Failed     3m18s (x6 over 4m59s)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    3m3s (x7 over 4m59s)   kubelet            Back-off pulling image "chronograf:1.9.1"
```

**Comment by timhallinflux** [comment]
we have this in Docker Hub....  https://hub.docker.com/_/chronograf
I can change the image location...

**Comment by timhallinflux** [comment]
we've stopped using quay.io for these images and are relying on Docker Hub going forward.  That said, I don't see where to alter this.

**Comment by rawkode** [comment]
@timhallinflux i think it's related to an outage: https://status.docker.com/

**Pull request merged**
