### PR TITLE
chore: allows for overridable ingress path

### PR DESCRIPTION
**Pull request by jgeth**
Modifies ingress path for chronograf and influxdb charts
Makes ingress path a template variable
Moves default path to values config
Bumps chart versions
Resolves: https://github.com/influxdata/helm-charts/issues/45

### CODE REVIEW

**Comment by rawkode** [comment]
@jgeth Can you bump the Chart version, please?

**Comment by jgeth** [comment]
> @jgeth Can you bump the Chart version, please?

@rawkode bumped versions

**Comment by geoff-coppertop** [comment]
I might be a bit late to the party but when I configure ingress.path to be anything but "/" I get a 404 response, am I missing something that is needed to make this work? I'm not having any issue when I put it on a subdomain, but that doesn't match the organization in my paths that I'm looking for.

**Comment by nat45928** [comment]
@geoff-coppertop I am seeing the same thing, did you find a solution?

**Comment by nat45928** [comment]
I figured this out. You need to specify a re-write rule in the ingress controller.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: influxdb
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts:
      - {host}
      secretName: {host}-tls
  rules:
    - host: {host}
      http:
        paths:
          - path: /influxdb(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: influxdb
                port:
                  number: 8086
```

See https://kubernetes.github.io/ingress-nginx/examples/rewrite/

**Pull request merged**
