### PR TITLE
Changing telegraf-operator kubeVersion to support EKS

### PR DESCRIPTION
**Pull request by leoblanc**
This PR fixes https://github.com/influxdata/helm-charts/issues/150

### CODE REVIEW

**Comment by russorat** [comment]
@leoblanc sorry for the delay here. You just need to bump the version and sign the cla, then we will be good to go: https://www.influxdata.com/legal/cla/

**Comment by leoblanc** [comment]
@russorat Hi, thanks for your info. I have signed the CLA. Regarding `bump the version`, what's the version I need to change? Thanks

**Comment by leoblanc** [comment]
Got it, it's the Chart version, I bumped the version with a new commit

**Review by russorat — APPROVED** [review]
LGTM

**Review by rawkode — APPROVED** [review]

**Comment by leoblanc** [comment]
Thanks!

**Pull request merged**
