### PR TITLE
Prepend basepath to liveness and readiness probes.

### PR DESCRIPTION
**Pull request by cpumanaz**
* Support Chronograf `--basepath`, `$BASE_PATH` options in chart.

- [x ] CHANGELOG.md updated (Uses documented Chronograf environment variable, env: {} is documented.)
    https://docs.influxdata.com/chronograf/v1.8/administration/config-options/#basepath-p
- [x ] Rebased/mergable
- [ x] Tests pass (See Below)
- [ x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

`helm template chronograf --set env.BASE_PATH="/chronograf"`

```
        env:
        - name: "BASE_PATH"
          value: "/chronograf"
        - name: "HOST_PAGE_DISABLED"
          value: "true"
        ports:
        - containerPort: 8888
          name: api
        livenessProbe:
          httpGet:
            path: /chronograf/ping
            port: api
        readinessProbe:
          httpGet:
            path: /chronograf/ping
            port: api
```

`helm template chronograf`

```
        env:
        - name: "HOST_PAGE_DISABLED"
          value: "true"
        ports:
        - containerPort: 8888
          name: api
        livenessProbe:
          httpGet:
            path: /ping
            port: api
        readinessProbe:
          httpGet:
            path: /ping
            port: api
```

### CODE REVIEW

**Comment by cpumanaz** [comment]
@russorat Are you available to review, or assign a second reviewer? Do you have an ETA on when this issue can be assigned for completion/merger. Currently our team CI is degraded. We would prefer not to fork/operate on a fork for Helm, and continue to use official releases.  We are currently pulling the fork branch and applying our Helm values to repair Chronograf after every helm install, but this is not sustainable and I have business pressure to fork so we can move on, and get our CI pipeline for Chronograf complete.

**Comment by rawkode** [comment]
Hi @cpumanaz,

I'm not sure about this change. The base path, when configuring Chronograf in a container, isn't too useful; as you still need to expose the service through an Ingress. That Ingress is where I'd expect the base path to be configured.

Can you clarify why this is needed, please?

**Comment by cpumanaz** [comment]
> Hi @cpumanaz,
> 
> I'm not sure about this change. The base path, when configuring Chronograf in a container, isn't too useful; as you still need to expose the service through an Ingress. That Ingress is where I'd expect the base path to be configured.
> 
> Can you clarify why this is needed, please?

@rawkode

**Comment by rawkode** [comment]
Most ingress do support rewriting for this scenario, with an annotation:

`ingress.kubernetes.io/rewrite-target: /`

If you don't think this is applicable in your case then we'll get this merged; I don't want you blocked any longer than it has been.

**Comment by cpumanaz** [comment]
> Most ingress do support rewriting for this scenario, with an annotation:
> 
> `ingress.kubernetes.io/rewrite-target: /`
> 
> If you don't think this is applicable in your case then we'll get this merged; I don't want you blocked any longer than it has been.

Why was the --basepath option even developed/documented, if the application always expected the web server to rewrite?

**Comment by cpumanaz** [comment]
> > Most ingress do support rewriting for this scenario, with an annotation:
> > `ingress.kubernetes.io/rewrite-target: /`
> > If you don't think this is applicable in your case then we'll get this merged; I don't want you blocked any longer than it has been.
> 
> Why was the --basepath option even developed/documented, if the application always expected the web server to rewrite?

Thank you. I was just trying to extend to Helm the same functionality that was developed/documented if helm wasn't used.

**Pull request merged**
