### PR TITLE
Update telegraf-operator to 1.3.6

### PR DESCRIPTION
**Pull request by wojciechka**

### CODE REVIEW

**Review by mkmik — DISMISSED** [review]

**Comment by JoshuaWatt** [comment]
Any chance #455 could get fixed first (since it seems that the operator version is tied to telegraf itself)?

**Comment by wojciechka** [comment]
@JoshuaWatt can you manually edit ClusterRole for telegraf-operator same as in https://github.com/influxdata/helm-charts/pull/454/commits/e1ba1f657a5f48e45136131ac8cae9d09e3a1c1d and see if it resolves your problem before I merge the PR?

**Comment by JoshuaWatt** [comment]
> @JoshuaWatt can you manually edit ClusterRole for telegraf-operator same as in [e1ba1f6](https://github.com/influxdata/helm-charts/commit/e1ba1f657a5f48e45136131ac8cae9d09e3a1c1d) and see if it resolves your problem before I merge the PR?

The syntax need updated (left comments on the commit), but once I did that it worked

**Review by timhallinflux — APPROVED** [review]

**Comment by wojciechka** [comment]
I will hold off on this until we can test additional changes to the helm-chart. Hopefully tomorrow.

**Review by mkmik — APPROVED** [review]

**Review by solomonope — APPROVED** [review]

**Review by GeorgeMac — APPROVED** [review]

**Pull request merged**
