### PR TITLE
[influxdb2] Bump to 2.7.1

### PR DESCRIPTION
**Pull request by centromere**

### CODE REVIEW

**Comment by max-os-lg** [comment]
What's going on here? Can we merge?

**Comment by orgads** [comment]
@powersj ping?

**Review by Philluxx — APPROVED** [review]
Looks good

**Review by Philluxx — APPROVED** [review]

**Comment by Philluxx** [comment]
Can someone please do another review to keep this going? Thanks a lot.

**Comment by jelmokri** [comment]
up ?

**Comment by centromere** [comment]
Hi @Philluxx. Is there anything required on my end to get this PR moved through the process?

**Review by mladBlum — APPROVED** [review]
Changes are fine!

**Comment by orgads** [comment]
Well? :)

**Comment by mladBlum** [comment]
> Well? :)

I did my best, sadly there is a reviewer with elevated rights needed. 
To the reviewer: I am running the chart since a few months with the influxdb image version overridden by 2.7.x and it works fine.

**Comment by centromere** [comment]
`v2.7.4` is released. If I update this PR, I believe it will require re-approval.

**Comment by MarkhamLee** [comment]
Just to add my $0.02 

- I updated the image version in the values.yaml file as well and haven't encountered any issues yet. 
- Until this is fixed anyone who installs the helm chart and then tries to connect to the latest Grafana will encounter an issue where the connection "works", but Grafana is unable to detect any measurements, even if you have data in InfluxDB. I.e. this is rapidly becoming a critical issue..

**Review by jeffreyssmith2nd — APPROVED** [review]

**Pull request merged**
