### PR TITLE
Added missing securityContext options

### PR DESCRIPTION
**Pull request by abhi1693**

### CODE REVIEW

**Comment by rawkode** [comment]
@abhi1693 You've kind of "slipped" the mountPath changes into this, but this will cause InfluxDB not to persist.

The following flag needs added to the `influxd` process: `influxd --engine-path=PATH`

https://docs.influxdata.com/influxdb/v2.0/reference/config-options/

**Comment by abhi1693** [comment]
@rawkode so, should I add the command to the statefulset? Also, does it need to have any other parameters if I were to override CMD of the docker?

**Comment by abhi1693** [comment]
@rawkode All fixed as per your suggestion

**Comment by rawkode** [comment]
Is there duplication with #252 ?

**Comment by abhi1693** [comment]
I'll close this one in favor of #252

**Pull request closed without merging**
