### PR TITLE
update enterprise version to latest release

### PR DESCRIPTION
**Pull request by idclark**
Updating Chart config to track the latest release 1.8.5.

### CODE REVIEW

**Comment by idclark** [comment]
#315 Issue raised to update Enterprise to latest release.

**Review by timhallinflux — APPROVED** [review]

**Comment by timhallinflux** [comment]
@idclark can you check the linter error?

**Comment by idclark** [comment]
`templates/: template: influxdb-enterprise/templates/meta-statefulset.yaml:40:20: executing "influxdb-enterprise/templates/meta-statefulset.yaml" at <.Values.license.secret>: nil pointer evaluating interface {}.secret` 

I interpret that as the linter not having access to a shared secret? Admittedly I'm a bit out of my element here as to how to resolve, but would help in any way i can if you tell me.

**Review by rawkode — APPROVED** [review]

**Comment by rawkode** [comment]
Yup! Forks don't get access to the testing secret. I'll add a fake secret for linting

**Comment by idclark** [comment]
> Yup! Forks don't get access to the testing secret. I'll add a fake secret for linting

I didn't know that. Thank you and sorry for the hassle!

**Pull request merged**
