### PR TITLE
Added metrics key to enable/disable internal metrics and minor bug fixes for influxdb2

### PR DESCRIPTION
**Pull request by abhi1693**
- [x] Bumped up the chart version
- [x] Updated `apiVersion` as Helmv2 is deprecated
- [x] Added `metrics.health.enabled` key to `values.yaml` to telegraf. This is disabled by default as it should be the user's choice to enable it.
- [x] Added `metrics.collect_memstats` key to `values.yaml` to telegraf
- [x] Updated `tag` to the latest version
- [x] Added helm resource-policy to influxdb2 pvc
- [x] Added `securityContext` to influxdb2

### CODE REVIEW

**Review by sumo-drosiek — APPROVED** [review]
LGTM, but I recommend to rebase on the top of the master branch due to https://github.com/influxdata/helm-charts/commit/f302281c9373ad6fbf1698998762401e252b29f4

**Comment by abhi1693** [comment]
@rawkode Any ETA on this?

**Comment by rawkode** [comment]
@abhi1693 There's a lot going on in this PR. I'd prefer it was split out in future, please.

I'll test this tomorrow 👍🏻

**Comment by abhi1693** [comment]
@rawkode I'll keep that in mind.

**Comment by abhi1693** [comment]
@rawkode Any update on this?

**Comment by abhi1693** [comment]
@rawkode If this cannot be merged, please let me know. I'll create my own chart and use that. As delays for this merge is costing us

**Review by rawkode — APPROVED** [review]

**Review by timhallinflux — APPROVED** [review]

**Comment by zmb3** [comment]
FYI folks, I filed issue #249 to fix an error with this PR.

**Pull request merged**
