### PR TITLE
[telegraf-operator] Keep support for helmv2

### LINKED ISSUE #187: [telegraf-operator] No support for helm2 (but declared)
Telegraf-operator helm charts declares support for `Helm v2 or later`, but `apiVersion: v2` is supported only by helm3. Either `Readme.md` or `Chart.yaml` should be updated

rel:
 
* https://helm.sh/docs/topics/charts/#the-apiversion-field
* https://github.com/influxdata/helm-charts/tree/master/charts/telegraf-operator#prerequisites

### PR DESCRIPTION
**Pull request by sumo-drosiek**
Keep support for helm2 as it's not end of life yet

Fixes #187

### CODE REVIEW

**Comment by russorat** [comment]
@rawkode i can't recall if there was a reason we did not want to support helm2 or not. any ideas?

**Comment by rawkode** [comment]
@russorat it's not that this chart removed support for Helm 2, it's that we opted not to support Helm 2 for any new charts we wrote. 

InfluxDB 2 and this operator never supported Helm 2.

I don't really see any reason to support Helm 2 either, as existing workloads on Helm 2 can coexist with workloads deployed with Helm 3.

Can you elaborate on your reasoning here, @sumo-drosiek?

Also, there's already automation in the root of the repo to build and publish the charts 👍

**Comment by sumo-drosiek** [comment]
@rawkode the reason for this PR, is that we want to use telegraf-operator as our chart dependency and we didn't drop the support for the helm2 yet.

We already find the workaround for this, so I will close that PR and prepare fix for README.md

**Comment by sumo-drosiek** [comment]
Sorry, accidentally pushed our local changes 🤦

**Pull request closed without merging**
