### PR TITLE
Make liveness/readiness/startup probes for influxdb2 chart configurable

### PR DESCRIPTION
**Pull request by wouterh**
This PR makes all kubernetes probes in the influxdb2 chart configurable in a way similar to what the influx v1 chart allows.

PR Checklist:

- [ ] CHANGELOG.md updated
- [ ] Rebased/mergable
- [ ] Tests pass
- [ ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Review by rawkode — APPROVED** [review]

**Review by rawkode — DISMISSED** [review]

**Comment by Tonow** [comment]
LGTM

**Comment by alespour** [comment]
it will not work with with existing custom values files without the new probe elements (results in `nil pointer evaluating interface {} ...`). I'm not sure if it's ok. If yes, then please ignore my comment.

Safer version would be eg.

```yaml
          {{- $livenessProbe := .Values.livenessProbe | default dict }}
          livenessProbe:
            httpGet:
              path: {{ $livenessProbe.path | default "/health" }}
              port: http
              scheme: {{ $livenessProbe.scheme | default "HTTP" }}
            initialDelaySeconds: {{ $livenessProbe.initialDelaySeconds | default 0 }}
            periodSeconds: {{ $livenessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ $livenessProbe.timeoutSeconds | default 1 }}
            failureThreshold: {{ $livenessProbe.failureThreshold | default 3 }}
          {{- $readinessProbe := .Values.readinessProbe | default dict }}
          readinessProbe:
            httpGet:
              path: {{ $readinessProbe.path | default "/health" }}
              port: http
              scheme: {{ $readinessProbe.scheme | default "HTTP" }}
            initialDelaySeconds: {{ $readinessProbe.initialDelaySeconds | default 0 }}
            periodSeconds: {{ $readinessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ $readinessProbe.timeoutSeconds | default 1 }}
            successThreshold: {{ $readinessProbe.successThreshold | default 1 }}
            failureThreshold: {{ $readinessProbe.failureThreshold | default 3 }}
          {{- $startupProbe := .Values.startupProbe | default dict }}
          {{- if $startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ $startupProbe.path | default "/health" }}
              port: http
              scheme: {{ $startupProbe.scheme | default "HTTP" }}
            initialDelaySeconds: {{ $startupProbe.initialDelaySeconds | default 30 }}
            periodSeconds: {{ $startupProbe.periodSeconds | default 5 }}
            timeoutSeconds: {{ $startupProbe.timeoutSeconds | default 1 }}
            failureThreshold: {{ $startupProbe.failureThreshold | default 6 }}
          {{- end }}
```

**Comment by alespour** [comment]
@wouterh You're right! Please ignore my comment.

**Review by alespour — DISMISSED** [review]

**Review by alespour — APPROVED** [review]

**Comment by alespour** [comment]
@timhallinflux could you please approve, I did a version bump myself so that we can move forward with this and that dismissed previous rawkode's approval. This (or any other `influxdb2`) pull request will also fix #400.

**Pull request merged**
