### PR TITLE
New telegraf configs features added to the configmap template

### PR DESCRIPTION
**Pull request by anachristofaro**
- Allows to provide a literal TOML config.
- Allows to provide a query.sh file from a literal BASH script to be used by the telegraf exec plugin.

Example:

```
  override_config:
    toml: |+
      [global_tags]
  
      [agent]
        interval = "10s"
        round_interval = true
        metric_batch_size = 1000
        metric_buffer_limit = 10000
        collection_jitter = "0s"
        flush_interval = "10s"
        flush_jitter = "0s"
        precision = ""
        hostname = ""
        omit_hostname = false
  
      [[outputs.influxdb]]
        urls = ["http://aci-monitor-influxdb.monitor:8086"]
        database = "telegraf"
        username = "telegraf"
            password = "telegraf"
      
      [[inputs.exec]]
        name_override = "ACI_APIC"
        commands = ["sh /etc/telegraf/query.sh /api/class/infraWiNode.json"]
        timeout = "10s"
        data_format = "json"
      
        json_query = "imdata"
        tag_keys = ["infraWiNode_attributes_nodeName", "infraWiNode_attributes_addr"]
        json_string_fields = ["*health", "*apicMode", "*adminSt", "*operSt", "*failoverStatus"]
      
        [inputs.exec.tags]
           apic = "${APIC_ADDRESS}"

  query_script:
    shell: |+
      #!/bin/bash
      #
      # Pipe bash arguments to variables
      operation=$1
      
      # Create cookie filename
      #cookiefilename=apic_cookie
      
      # APIC Login and store session cookie to /tmp
      curl -s -k -d "<aaaUser name=${APIC_USER} pwd=${APIC_PASSWORD}/>" -c /tmp/cookiefile -X POST https://${APIC_ADDRESS}/api/mo/aaaLogin.xml > /dev/null
      
      # APIC Query Operation using the session cookie
      curl -s -k -X GET https://${APIC_ADDRESS}$operation -b /tmp/cookiefile
      
      # APIC Logout
      curl -s -k -d "<aaaUser name=${APIC_USER}/>" -X POST https://${APIC_ADDRESS}/api/mo/aaaLogout.json -b /tmp/cookiefile > /dev/null
      
      # Remove session cookie
      # rm -f /tmp/cookiefile


```

### CODE REVIEW

**Comment by rawkode** [comment]
Can you explain the query script, please?

I'd also encourage calling the toml value `config_toml` and documenting that it replaces all other config options

**Comment by anachristofaro** [comment]
The main purpose of query_script.sh is to allow the same script to be reused by more than one [[inputs.exec]] for different query parameters based on bash arguments. In addition, it also allows the user to enter a set of commands to be performed by the [[inputs.exec]] in a more fashion way.

Next, an example of multiple queries that I'm using in my application. As a requirement of the application, in each query it is necessary to generate a new token. That is, each [[inputs.exec]] command runs the script that perform the login in to the server to generates a token, makes the query using this token, and logout.

```
  config_toml: |+
      [global_tags]
  
      [agent]
        interval = "30s"
        round_interval = true
        metric_batch_size = 1000
        metric_buffer_limit = 10000
        collection_jitter = "0s"
        flush_interval = "30s"
        flush_jitter = "0s"
        precision = ""
        hostname = ""
        omit_hostname = false
  
      [[outputs.influxdb]]
        urls = ["http://aci-monitor-influxdb.monitor:8086"]
        database = "telegraf"
        username = "telegraf"
            password = "telegraf"
      
      [[inputs.exec]]
        name_override = "ACI_APIC"
        commands = ["sh /etc/telegraf/query.sh /api/class/infraWiNode.json"]
        timeout = "30s"
        data_format = "json"
      
        json_query = "imdata"
        tag_keys = ["infraWiNode_attributes_nodeName", "infraWiNode_attributes_addr"]
        json_string_fields = ["*health", "*apicMode", "*adminSt", "*operSt", "*failoverStatus"]
      
        [inputs.exec.tags]
           apic = "${APIC_ADDRESS}"
      
      [[inputs.exec]]
        name_override = "ACI_Faults"
        commands = ["sh /etc/telegraf/query.sh /api/class/faultCountsWithDetails.json"]
        timeout = "30s"
        data_format = "json"
      
        json_query = "imdata"
        json_string_fields = ["faultCountsWithDetails_attributes_crit", "faultCountsWithDetails_attributes_maj", "faultCountsWithDetails_attributes_minor", "faultCountsWithDetails_attributes_warn"]
      
        [inputs.exec.tags]
           apic = "${APIC_ADDRESS}"
      
      [[processors.converter]]
        namepass = ["ACI_Faults"]
      
        [processors.converter.fields]
          integer = ["*faultCountsWithDetails*"]
      
      [[inputs.exec]]
        name_override = "ACI_NodeHealth"
        commands = ["sh /etc/telegraf/query.sh /api/class/topSystem.json?rsp-subtree-include=health"]
        timeout = "30s"
        data_format = "json"
      
        json_query = "imdata"
        tag_keys = ["topSystem_attributes_name", "topSystem_attributes_oobMgmtAddr", "topSystem_attributes_podId", "topSystem_attributes_role"]
        json_string_fields = ["*attributes_cur", "*systemUpTime", "*state"]
      
        [inputs.exec.tags]
           apic = "${APIC_ADDRESS}"
      
      [[processors.converter]]
        namepass = ["ACI_NodeHealth"]
      
        [processors.converter.fields]
          integer = ["topSystem_children_0_healthInst_attributes_cur"]
      
      [[inputs.exec]]
        name_override = "ACI_SystemHealth"
        commands = ["sh /etc/telegraf/query.sh /api/class/fabricHealthTotal.json"]
        timeout = "30s"
        data_format = "json"
      
        json_query = "imdata"
        tag_keys = ["fabricHealthTotal_attributes_dn"]
        json_string_fields = ["*cur"]
      
        [inputs.exec.tags]
           apic = "${APIC_ADDRESS}"
      
      [[processors.converter]]
        namepass = ["ACI_SystemHealth"]
      
        [processors.converter.fields]
          integer = ["fabricHealthTotal_attributes_cur"]
      
      [[processors.regex]]
        namepass = ["ACI_SystemHealth"]
      
        [[processors.regex.tags]]
          key = "fabricHealthTotal_attributes_dn"
          pattern = "topology/"
          replacement = ""
      
      [[inputs.exec]]
        name_override = "ACI_TenantHealth"
        commands = ["sh /etc/telegraf/query.sh /api/class/fvTenant.json?rsp-subtree-include=health"]
        timeout = "30s"
        data_format = "json"
      
        json_query = "imdata"
        tag_keys = ["fvTenant_attributes_name"]
        json_string_fields = ["*cur"]
      
        [inputs.exec.tags]
           apic = "${APIC_ADDRESS}"
      
      [[processors.converter]]
        namepass = ["ACI_TenantHealth"]
      
        [processors.converter.fields]
          integer = ["fvTenant_children_0_healthInst_attributes_cur"]

  query_script:
    shell: |+
      #!/bin/bash
      #
      # Pipe bash arguments to variables
      operation=$1
      
      # Create session cookiefile name
      cookiefile=cookie_$(openssl rand -base64 12)
      
      # APIC Login and store session cookie to /etc/telegraf
      curl -s -k -d "<aaaUser name=${APIC_USER} pwd=${APIC_PASSWORD}/>" -c /tmp/$cookiefile -X POST https://${APIC_ADDRESS}/api/mo/aaaLogin.xml > /dev/null
      
      # APIC Query Operation using the session cookie
      curl -s -k -X GET https://${APIC_ADDRESS}$operation -b /tmp/$cookiefile
      
      # APIC Logout
      curl -s -k -d "<aaaUser name=${APIC_USER}/>" -X POST https://${APIC_ADDRESS}/api/mo/aaaLogout.json -b /tmp/$cookiefile > /dev/null
      
      # Remove session cookie
      rm -f /tmp/$cookiefile
      
```

Please, let me know if config_toml shown in the example is as you expect.

**Comment by anachristofaro** [comment]
> Can you explain the query script, please?
> 
> I'd also encourage calling the toml value `config_toml` and documenting that it replaces all other config options

**Comment by anachristofaro** [comment]
> Can you explain the query script, please?
> 
> I'd also encourage calling the toml value `config_toml` and documenting that it replaces all other config options

Something went wrong with the pull request. Let me know if it’s of interest that I can open a new one.

**Comment by foobaar** [comment]
@anachristofaro i'm looking to do exactly what you did in this pull request.

**Pull request closed without merging**
