### PR TITLE
Make sidecar default resources configurable

### PR DESCRIPTION
**Pull request by korjek**
When default sidecar resources don't fit someone's need it's
preferable to specify a custom default value instead of adding annotations
to every pod that runs sidecar.
So this PR exposes variables to configure default sidecar resources.

This was tested by specifying custom values for default resources and deploying to k8s.
`kubectl describe pod` showed that telegraf sidecar has resources specified using `values.yaml`

### CODE REVIEW

**Comment by korjek** [comment]
@jaymebrd sorry for bothering you, but not sure who should be tagged.
Could you please advice who can helm with pushing this PR forward?

**Comment by korjek** [comment]
@powersj @sspaink guys, probably you can take a look or assign the right person, please

**Comment by korjek** [comment]
@wojciechka could you please take a look?

**Comment by wojciechka** [comment]
> @wojciechka could you please take a look?

Hi @korjek, I apologize, this got lost in my notifications.

Can you update the chart version as we've released telegraf-operator and chart in the meantime? It should then be possible to run and merge it.

This will cause a tiny issue, because we're trying to align telegraf-operator and helm chart version for automation purposes, but we'll work it out.

**Comment by korjek** [comment]
@wojciechka sorry, I completely lost track of this PR.
Updated.

**Comment by korjek** [comment]
@wojciechka could we proceed with this PR, please?

**Review by jaymebrd — APPROVED** [review]

**Comment by korjek** [comment]
@jeffreyssmith2nd @srebhan could anyone take a look, please?

**Review by powersj — APPROVED** [review]

**Review by jeffreyssmith2nd — APPROVED** [review]

**Pull request merged**
