### PR TITLE
Removed duplicated HOSTIP

### PR DESCRIPTION
**Pull request by caiocfer**
When telegraf-ds helm chart is deployed the HOSTIP env arg is duplicated in the daemonset.

### CODE REVIEW

**Comment by caiocfer** [comment]
Could someone take a look? It's just a fix to a duplicated arg.
@powersj @srebhan @alespour @jeffreyssmith2nd

**Comment by powersj** [comment]
Could you please also file an issue and demonstrate how this duplication shows up?

**Comment by caiocfer** [comment]
Just published the issue: 
https://github.com/influxdata/helm-charts/issues/608

**Comment by powersj** [comment]
@caiocfer thanks - can you update the version in your PR please?

**Review by powersj — APPROVED** [review]

**Pull request merged**
