### PR TITLE
Fix UDP support for influxdb

### PR DESCRIPTION
**Pull request by jyaworski**

### CODE REVIEW

**Comment by gitirabassi** [comment]
@jyaworski have you tested this feature in your cluster?

**Comment by jyaworski** [comment]
@gitirabassi I confirmed that the service endpoint resolved in the ingress and everything generally looked OK.

**Comment by gitirabassi** [comment]
which ingress-controller are you running? @jyaworski

**Comment by jyaworski** [comment]
nginx-ingress and https://github.com/haproxytech/kubernetes-ingress

To be clear, I was not able to test UDP over ingress in my test. I tested in-cluster UDP.

**Comment by gitirabassi** [comment]
Most ingress, if not all don't support this specification. Can you can you remove the ingress changes and leaving the rest?

**Comment by jyaworski** [comment]
@gitirabassi done

**Pull request merged**
