### PR TITLE
set collectd service as a UDP service

### LINKED ISSUE #107: The collectd service uses TCP when it should use UDP
The [collectd service template](https://github.com/influxdata/helm-charts/blob/master/charts/influxdb/templates/service.yaml#L28) does not specify the UDP protocol and therefore launches as TCP. However, the [collectd service uses UDP](https://docs.influxdata.com/influxdb/v1.8/supported_protocols/collectd/) and not TCP. Manually editing the deployment to use UDP allowed traffic to flow in.

### PR DESCRIPTION
**Pull request by aureq**
This commit sets `collectd` service as UDP instead of TCP.

fixes #107

### CODE REVIEW

**Comment by naseemkullah** [comment]
Thanks @aureq! Please bump the chart version.

**Comment by naseemkullah** [comment]
We just released 4.7.1 https://github.com/influxdata/helm-charts/blob/master/charts/influxdb/Chart.yaml can you please rebase and bump to 4.7.2?

**Comment by aureq** [comment]
Hi @naseemkullah Updated the PR. Let me know if this is good on your side.

**Comment by naseemkullah** [comment]
lgtm @aureq but we'll need a second approval

**Pull request merged**
