### PR TITLE
fix: add startupProbe to influxdb2 chart 

### PR DESCRIPTION
**Pull request by peterpeerdeman**
to avoid killing the container too soon while influx is still booting on armv8 (raspberrypi). Without this tweak I could not get influxdb2 chart running on a k3s raspberry pi cluster.

### CODE REVIEW

**Review by fiskhest — COMMENTED** [review]
Confirming I am seeing the same issue on a single-node default k3s armv8/arm64 install and the proposed changes fixes it. LGTM!

**Review by timhallinflux — APPROVED** [review]

**Comment by timhallinflux** [comment]
@peterpeerdeman please bump the chart version and we'll merge.

**Comment by peterpeerdeman** [comment]
Hi @timhallinflux I've bumped the version and pushed the commit 👍

**Comment by alespour** [comment]
Solved in #381

**Pull request closed without merging**
